Telecominfraproject/wlan-cloud-services

- manufacturer-service/src/main/resources/manufacturer-service-openapi.yaml
> Manufacturer service openapi

- firmware-service/src/main/resources/firmware-service-openapi.yaml
> Firmware service openapi documentation

- portal-services/src/main/java/com/telecominfraproject/wlan/portal/controller/profile/ProfilePortalController.java
- portal-services/src/main/resources/portal-services-openapi.yaml
- profile-datastore-common-test/src/main/java/com/telecominfraproject/wlan/profile/datastore/BaseProfileDatastoreTest.java
- profile-datastore-inmemory/src/main/java/com/telecominfraproject/wlan/profile/datastore/inmemory/ProfileDatastoreInMemory.java
- profile-datastore-inmemory/src/test/java/com/telecominfraproject/wlan/profile/datastore/inmemory/ProfileDatastoreInMemoryTests.java
- profile-datastore-interface/src/main/java/com/telecominfraproject/wlan/profile/datastore/ProfileDatastore.java
- profile-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/profile/datastore/rdbms/ProfileDAO.java
- profile-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/profile/datastore/rdbms/ProfileDatastoreRdbms.java
- profile-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/profile/datastore/rdbms/SqlQueryBuilder.java
- profile-datastore-rdbms/src/test/java/com/telecominfraproject/wlan/profile/datastore/rdbms/ProfileDatastoreRdbmsTests.java
- profile-models/src/main/java/com/telecominfraproject/wlan/profile/models/ProfileByCustomerRequest.java
- profile-models/src/main/java/com/telecominfraproject/wlan/profile/models/ProfileByCustomerRequestFactory.java
- profile-service-interface/src/main/java/com/telecominfraproject/wlan/profile/ProfileServiceInterface.java
- profile-service-local/src/main/java/com/telecominfraproject/wlan/profile/ProfileServiceLocal.java
- profile-service-remote/src/main/java/com/telecominfraproject/wlan/profile/ProfileServiceRemote.java
- profile-service-remote/src/test/java/com/telecominfraproject/wlan/profile/ProfileServiceRemoteTest.java
- profile-service/src/main/java/com/telecominfraproject/wlan/profile/controller/ProfileController.java
- profile-service/src/main/resources/profile-service-openapi.yaml
- profile-service/src/test/java/com/telecominfraproject/wlan/profile/controller/ProfileControllerTest.java
Add new optional argument to /portal/profile/getForCustomer and /api/profile/getForCustomer APIs
Some refactoring with intent to improve code readability
> Wifi 966 add profile type to /portal/profile/for customer api

- portal-services/src/main/java/com/telecominfraproject/wlan/portal/controller/profile/ProfilePortalController.java
- profile-datastore-common-test/src/main/java/com/telecominfraproject/wlan/profile/datastore/BaseProfileDatastoreTest.java
- profile-datastore-inmemory/src/main/java/com/telecominfraproject/wlan/profile/datastore/inmemory/ProfileDatastoreInMemory.java
- profile-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/profile/datastore/rdbms/ProfileDAO.java
- profile-models/src/main/java/com/telecominfraproject/wlan/profile/models/ProfileByCustomerRequest.java
- profile-models/src/main/java/com/telecominfraproject/wlan/profile/models/ProfileByCustomerRequestFactory.java
- profile-service-interface/src/main/java/com/telecominfraproject/wlan/profile/ProfileServiceInterface.java
- profile-service-local/src/main/java/com/telecominfraproject/wlan/profile/ProfileServiceLocal.java
- profile-service-remote/src/main/java/com/telecominfraproject/wlan/profile/ProfileServiceRemote.java
- profile-service-remote/src/test/java/com/telecominfraproject/wlan/profile/ProfileServiceRemoteTest.java
- profile-service/src/main/java/com/telecominfraproject/wlan/profile/controller/ProfileController.java
Add the capability to filter the Profile by Customer API by using a substring of the profile name.
This is not visible in the yaml files for TIP as per intent.
> Wifi 1005 change db backend to support search by substring

- all-cloud-and-opensync-gw-in-one-docker/src/main/docker-with-mqtt/app/opensync/LocationBuildingExample.json
- all-cloud-and-opensync-gw-in-one-docker/src/main/docker-with-mqtt/app/opensync/LocationBuildingParentExample.json
- all-cloud-and-opensync-gw-in-one-docker/src/main/docker/app/opensync/LocationBuildingExample.json
- all-cloud-and-opensync-gw-in-one-docker/src/main/docker/app/opensync/LocationBuildingParentExample.json
- location-models/src/main/java/com/telecominfraproject/wlan/location/models/LocationActivityDetails.java
- location-models/src/main/java/com/telecominfraproject/wlan/location/models/LocationDetails.java
Remove lastBusySnapshot and align method naming
> Clean up LocationActivityDetails

- portal-services/src/main/java/com/telecominfraproject/wlan/portal/controller/portaluser/PortalUserPortalController.java
- portal-services/src/main/resources/portal-services-openapi.yaml
- portal-user-datastore-common-test/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/BasePortalUserDatastoreTest.java
- portal-user-datastore-inmemory/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/inmemory/PortalUserDatastoreInMemory.java
- portal-user-datastore-interface/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/PortalUserDatastore.java
- portal-user-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/rdbms/PortalUserDAO.java
- portal-user-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/rdbms/PortalUserDatastoreRdbms.java
- portal-user-service-interface/src/main/java/com/telecominfraproject/wlan/portaluser/PortalUserServiceInterface.java
- portal-user-service-local/src/main/java/com/telecominfraproject/wlan/portaluser/PortalUserServiceLocal.java
- portal-user-service-remote/src/main/java/com/telecominfraproject/wlan/portaluser/PortalUserServiceRemote.java
- portal-user-service-remote/src/test/java/com/telecominfraproject/wlan/portaluser/PortalUserServiceRemoteTest.java
- portal-user-service/src/main/java/com/telecominfraproject/wlan/portaluser/controller/PortalUserController.java
- portal-user-service/src/main/resources/portaluser-service-openapi.yaml
Tagging related story : https://telecominfraproject.atlassian.net/browse/WIFI-1108
> Adding endpoint for getCustomerIdsFromUsername

- all-cloud-in-one-process/src/main/java/com/telecominfraproject/wlan/startuptasks/AllInOneStartListener.java
- portal-services/src/main/java/com/telecominfraproject/wlan/portal/controller/webtoken/WebTokenIntrospectorController.java
- portal-services/src/main/resources/portal-services-openapi.yaml
- portal-user-datastore-common-test/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/BasePortalUserDatastoreTest.java
- portal-user-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/rdbms/PortalUserDAO.java
- portal-user-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/rdbms/PortalUserRowMapper.java
- portal-user-datastore-rdbms/src/main/resources/schema-postgresql.sql
- portal-user-datastore-rdbms/src/test/resources/schema-hsqldb-test.sql
- portal-user-datastore-rdbms/src/test/resources/test-data.sql
- portal-user-models/src/main/java/com/telecominfraproject/wlan/portaluser/models/PortalUser.java
- portal-user-service-remote/src/test/java/com/telecominfraproject/wlan/portaluser/PortalUserServiceRemoteTest.java
- portal-user-service/src/main/resources/portaluser-service-openapi.yaml
Story ref: https://telecominfraproject.atlassian.net/browse/WIFI-1122
> Adding support for list<PortalUserRole>

- profile-service/src/main/java/com/telecominfraproject/wlan/profile/controller/ProfileController.java
- profile-service/src/test/java/com/telecominfraproject/wlan/profile/controller/ProfileControllerTest.java
Adding validation on creating profiles with the same name and same ProfileType.
> WIFI 1149 profile unique name validation

- equipment-service/src/main/resources/equipment-service-openapi.yaml
- portal-services/src/main/resources/portal-services-openapi.yaml
- portal-user-service/src/main/resources/portaluser-service-openapi.yaml
- profile-service/src/main/resources/profile-service-openapi.yaml
Syncing up portal yamls with missing properties or examples
> WIFI-1201 Sync Portal YAML

- location-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/location/datastore/rdbms/LocationDAO.java
- location-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/location/datastore/rdbms/LocationRowMapper.java
- location-datastore-rdbms/src/main/resources/schema-postgresql.sql
- location-datastore-rdbms/src/test/resources/schema-hsqldb-test.sql
Added column as the last column in table `equipment_location` since Alter table will add the column in the end.
> WIFI-1208: Update equipment_location table by adding a new column detailsBin of type bytea

- location-datastore-common-test/src/main/java/com/telecominfraproject/wlan/location/datastore/BaseLocationDatastoreTest.java
- location-datastore-inmemory/src/main/java/com/telecominfraproject/wlan/location/datastore/inmemory/LocationDatastoreInMemory.java
- location-datastore-interface/src/main/java/com/telecominfraproject/wlan/location/datastore/LocationDatastore.java
- location-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/location/datastore/rdbms/LocationDAO.java
- location-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/location/datastore/rdbms/LocationDatastoreRdbms.java
- location-models/src/main/java/com/telecominfraproject/wlan/location/models/LocationDetails.java
- location-service-interface/src/main/java/com/telecominfraproject/wlan/location/service/LocationServiceInterface.java
- location-service-local/src/main/java/com/telecominfraproject/wlan/location/service/LocationServiceLocal.java
- location-service-remote/src/main/java/com/telecominfraproject/wlan/location/service/LocationServiceRemote.java
- location-service-remote/src/test/java/com/telecominfraproject/wlan/location/service/LocationServiceRemoteTest.java
- location-service/src/main/java/com/telecominfraproject/wlan/location/service/LocationServiceController.java
- location-service/src/main/resources/location-service-openapi.yaml
WIFI-1331 Add getAllAncestors API support in LocationService
> WIFI-1331 Add getAllAncestors API support in LocationService

- dashboard-sp/src/main/java/com/telecominfraproject/wlan/streams/dashboard/CustomerPortalDashboardAggregator.java
- dashboard-sp/src/main/java/com/telecominfraproject/wlan/streams/dashboard/CustomerPortalDashboardPartialAggregator.java
- dashboard-sp/src/main/java/com/telecominfraproject/wlan/streams/dashboard/CustomerPortalDashboardPartialContext.java
- status-models/src/main/java/com/telecominfraproject/wlan/status/dashboard/models/CustomerPortalDashboardStatus.java
- status-models/src/main/java/com/telecominfraproject/wlan/status/dashboard/models/events/CustomerPortalDashboardPartialEvent.java
- status-models/src/test/java/com/telecominfraproject/wlan/status/dashboard/models/CustomerPortalDashboardTests.java
- system-event-models/src/main/java/com/telecominfraproject/wlan/systemevent/aggregation/models/CustomerPortalDashboardPartialEvent.java
CustomerPortalDashboardStatus contains alarmCount map by severity (StatusCode)
The alarmCount map is incremented by the CustomerPortalDashboardPartialEvent object as they are processed by the aggregator.
PartialEvents with alarmCount data are generated by CustomerPortalDashboardPartialAggregator
> [WIFI-1545] Adding alarmCountBySeverity to CustomerPortalDashboardStatus

- equipment-models/src/main/java/com/telecominfraproject/wlan/equipment/models/bulkupdate/rrm/EquipmentRrmBulkUpdateItem.java
Same bugfix as WIFI-1561 but also required on applyToEquipment
> [WIFI-1591] Bugfix on applyToEquipment to reach default state if null

- equipment-gateway-models/src/main/java/com/telecominfraproject/wlan/equipmentgateway/models/CEGWFirmwareDownloadRequest.java
- equipment-gateway-service-interface/src/main/resources/equipment-gateway-service-openapi.yaml
- firmware-models/src/main/java/com/telecominfraproject/wlan/firmware/models/FirmwareVersion.java
- firmware-models/src/main/java/com/telecominfraproject/wlan/firmware/models/ValidationMethod.java
- firmware-service/src/main/java/com/telecominfraproject/wlan/firmware/controller/FirmwareController.java
- firmware-service/src/main/resources/firmware-service-openapi.yaml
- firmware-service/src/test/java/com/telecominfraproject/wlan/firmware/controller/FirmwareControllerTest.java
- portal-services/src/main/java/com/telecominfraproject/wlan/portal/controller/equipmentgateway/EquipmentGatewayPortalController.java
- portal-services/src/main/resources/portal-services-openapi.yaml
…tionCode for FirmwareVersion create, added FirmwareMethod.NONE
- Removed validation checks
- Added ValidationMethod.NONE as a default state for optional validationMethod input (validationMethod = null)
- Removed unused validationCode and validationMethod fields from CEGWFirmwareDownloadRequest as Mike suggested related to the validation fields. 
To be merged with https://github.com/Telecominfraproject/wlan-cloud-opensync-controller/pull/27
> [WIFI-1593] remove validation checks on FirmwareVersion create

- dashboard-sp/src/main/java/com/telecominfraproject/wlan/streams/dashboard/CustomerPortalDashboardPartialAggregator.java
- dashboard-sp/src/main/java/com/telecominfraproject/wlan/streams/dashboard/CustomerPortalDashboardPartialContext.java
- status-models/src/main/java/com/telecominfraproject/wlan/status/dashboard/models/events/CustomerPortalDashboardPartialEvent.java
- AP Inservice count now gets updated when AP gets disconnected
- Deleting the AP does not add up in service count anymore
- Associated Clients get updated as well
> WIFI-1641: Dashboard: Number of "In service APs" is not accurate

- profile-models/src/main/java/com/telecominfraproject/wlan/profile/ssid/models/SsidConfiguration.java
Make constants BANDWIDTH_LIMIT_MAX, RADIUS_ACCOUNTING_SERVICE_INTERVAL_MIN, RADIUS_ACCOUNTING_SERVICE_INTERVAL_MAX, MAX_SSID_LENGTH configurable via system properties
> Make some SsidConfiguration constants configurable

- profile-models/src/main/java/com/telecominfraproject/wlan/profile/ssid/models/SsidConfiguration.java
- profile-models/src/main/java/com/telecominfraproject/wlan/profile/ssid/models/SsidExceedsMaxLengthException.java
- profile-models/src/test/java/com/telecominfraproject/wlan/profile/ssid/models/SsidConfigurationTests.java
Fix setter method to use actual provided value for radiusAcountingServiceInterval instead of default min value of 60.
> Propogate WIFI-1440 fix to release branch

- alarm-datastore-cassandra/src/main/java/com/telecominfraproject/wlan/alarm/datastore/cassandra/AlarmDatastoreCassandra.java
- alarm-datastore-cassandra/src/test/java/com/telecominfraproject/wlan/alarm/datastore/cassandra/AlarmDatastoreCassandraTests.java
- alarm-datastore-common-test/src/main/java/com/telecominfraproject/wlan/alarm/datastore/BaseAlarmDatastoreTest.java
- alarm-service-remote/src/test/java/com/telecominfraproject/wlan/alarm/AlarmServiceRemoteTest.java
> Wifi 1729 alarm acknowledged update table

- location-service-interface/src/main/java/com/telecominfraproject/wlan/location/service/LocationServiceInterface.java
- location-service-local/src/main/java/com/telecominfraproject/wlan/location/service/LocationServiceLocal.java
- location-service-remote/src/main/java/com/telecominfraproject/wlan/location/service/LocationServiceRemote.java
- location-service-remote/src/test/java/com/telecominfraproject/wlan/location/service/LocationServiceRemoteTest.java
- location-service/src/main/java/com/telecominfraproject/wlan/location/service/LocationServiceController.java
- location-service/src/main/resources/location-service-openapi.yaml
there was no getOrNull api in the location service, so i'm adding one at endpoint /api/location/orNull
> Wifi 2373 add get or null api to location service

- client-models/src/main/java/com/telecominfraproject/wlan/client/models/events/ClientAddedEvent.java
- client-models/src/main/java/com/telecominfraproject/wlan/client/models/events/ClientBlockListChangedEvent.java
- client-models/src/main/java/com/telecominfraproject/wlan/client/models/events/ClientChangedEvent.java
- client-models/src/main/java/com/telecominfraproject/wlan/client/models/events/ClientRemovedEvent.java
- client-models/src/main/java/com/telecominfraproject/wlan/client/models/events/ClientSessionChangedEvent.java
- client-models/src/main/java/com/telecominfraproject/wlan/client/models/events/ClientSessionClosedEvent.java
- client-models/src/main/java/com/telecominfraproject/wlan/client/models/events/ClientSessionRemovedEvent.java
Added Client Mac Address to Client Session System Events
> WIFI-2398 Adding ClientMac to client session system events

- portal-user-datastore-rdbms/src/main/java/com/telecominfraproject/wlan/portaluser/datastore/rdbms/PortalUserDAO.java
increase visibility of some fields in PortalUserDAO to allow classes to extend upon without duplication of values
> WIFI-2698-Update-visibility-of-fields-in-PortalUserDAO

- portal-services/pom.xml
- portal-services/src/main/java/com/telecominfraproject/wlan/portal/controller/profile/ProfilePortalController.java
- portal-services/src/test/java/com/telecominfraproject/wlan/portal/controller/profile/ProfilePortalControllerTest.java
- rework the algorithm for the api at endpoint /portal/profile/equipmentCounts to include the correct child profile count for equipment
- create test case to cover this api
> WIFI-2699  Modify GET /portal/profile/equipmentCounts to support child profiles for the count

- alarm-service-remote/pom.xml
- alarm-service/pom.xml
- alarm-service/src/test/java/com/telecominfraproject/wlan/alarm/controller/AlarmControllerTest.java
- cloud-event-dispatcher-remote/pom.xml
- equipment-service-remote/pom.xml
- equipment-service/pom.xml
- equipment-service/src/main/java/com/telecominfraproject/wlan/equipment/controller/EquipmentController.java
- equipment-service/src/test/java/com/telecominfraproject/wlan/equipment/controller/EquipmentControllerTest.java
- portal-services/pom.xml
- portal-services/src/test/java/com/telecominfraproject/wlan/portal/controller/profile/ProfilePortalControllerTest.java
The necessary changes are in the EquipmentController.java. Other files are adding dependencies to pass all tests.
> [WIFI-2970] add equipment admin status when switching customer

- equipment-service/src/main/java/com/telecominfraproject/wlan/equipment/controller/EquipmentController.java
After switching customers, country code will be empty and ipAddress shows N/A. Keeping protocol status will fix the issue.
> [WIFI-2987] add protocol status when switching customer

- equipment-service/src/main/java/com/telecominfraproject/wlan/equipment/controller/EquipmentController.java
Current if statement location will prevent customer details to migrate to new customer.
> [WIFI-3041] move if statusment for custmerId check to a different location

- service-metric-models/src/main/java/com/telecominfraproject/wlan/servicemetric/apnode/models/ApNodeMetrics.java
- service-metric-models/src/main/java/com/telecominfraproject/wlan/servicemetric/apssid/models/SsidStatistics.java
- service-metric-models/src/main/java/com/telecominfraproject/wlan/servicemetric/client/models/ClientMetrics.java
- service-metric-models/src/main/java/com/telecominfraproject/wlan/servicemetric/client/models/ClientRadioUtils.java
- service-metric-models/src/main/java/com/telecominfraproject/wlan/servicemetric/client/qoe/models/ClientQoEMetrics.java
- service-metric-models/src/main/java/com/telecominfraproject/wlan/servicemetric/models/McsStats.java
- service-metric-models/src/main/java/com/telecominfraproject/wlan/servicemetric/models/McsType.java
- service-metric-models/src/main/java/com/telecominfraproject/wlan/servicemetric/models/WmmQueueStats.java
Reverts Telecominfraproject/wlan-cloud-services#144
> Revert "[WIFI 3358] Client Metrics report performance improvements"

- port-forwarding-gateway/src/main/java/com/telecominfraproject/wlan/portforwardinggateway/websocket/PortForwarderWebSocketHandler.java
> Fix to not remove the active sessions.
